kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "tide.name" . }}
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - environments
      - pipelineactivities
      - sourcerepositories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
